name: Lint
on: [push, pull_request]

jobs:
    phpstan:
        name: ubuntu v4
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run
              run:  apt list --installed

            - name: Run php -m
              run:  php -m

            - name: Run php xdebug
              run:  php --ri=xdebug
